import { describe, it, expect } from "vitest";
import { parseGuide } from "./reviewGuide.ts";

const FILES = [
  "server/scheduler.ts",
  "server/scheduler.test.ts",
  "web/src/App.tsx",
  "web/src/query_notification_subscriptions.test.ts",
  "package-lock.json",
];

const GUIDE = `This PR adds a scheduler and wires it into the app shell.
Read the core first; the lockfile is churn.

## The scheduler itself
Adds the queue and the run loop. Everything else follows from this.
Impact: a bad ordering here silently drops jobs.
Files: server/scheduler.ts, server/scheduler.test.ts

## Wiring it into the UI
Mounts the scheduler's status in the app shell. Low risk.
Files: \`web/src/App.tsx\`

## Churn
Regenerated by npm.
Files: package-lock.json
`;

describe("parseGuide", () => {
  const g = parseGuide(GUIDE, FILES);

  it("keeps the prose before the first heading as the intro", () => {
    expect(g.intro).toContain("adds a scheduler");
    expect(g.intro).not.toContain("The scheduler itself");
  });

  it("keeps the guide's section order, not the diff's file order", () => {
    expect(g.sections.map((s) => s.title)).toEqual([
      "The scheduler itself",
      "Wiring it into the UI",
      "Churn",
    ]);
  });

  it("files each section's paths, backticked or bare", () => {
    expect(g.sections[0].files).toEqual([
      "server/scheduler.ts",
      "server/scheduler.test.ts",
    ]);
    expect(g.sections[1].files).toEqual(["web/src/App.tsx"]);
    expect(g.sections[2].files).toEqual(["package-lock.json"]);
  });

  it("keeps the explanation as the body and drops the Files line from it", () => {
    expect(g.sections[0].body).toContain("Adds the queue");
    expect(g.sections[0].body).toContain("Impact:");
    expect(g.sections[0].body).not.toContain("Files:");
  });

  it("reports the files no section grouped", () => {
    expect(g.leftover).toEqual(["web/src/query_notification_subscriptions.test.ts"]);
  });

  it("orders a section's files the way the diff does", () => {
    const out = parseGuide(
      "## S\nwhy\nFiles: web/src/App.tsx, server/scheduler.ts",
      FILES,
    );
    expect(out.sections[0].files).toEqual(["server/scheduler.ts", "web/src/App.tsx"]);
  });

  it("accepts a bulleted file list", () => {
    const out = parseGuide(
      "## S\nwhy\nFiles:\n- `server/scheduler.ts`\n- server/scheduler.test.ts\n\nmore prose",
      FILES,
    );
    expect(out.sections[0].files).toEqual([
      "server/scheduler.ts",
      "server/scheduler.test.ts",
    ]);
    expect(out.sections[0].body).toContain("more prose");
  });

  it("tolerates a shortened path and Paths: as the label", () => {
    const out = parseGuide("## S\nwhy\n**Paths**: `App.tsx`", FILES);
    expect(out.sections[0].files).toEqual(["web/src/App.tsx"]);
  });

  it("does not let a snake_case path be mangled by emphasis stripping", () => {
    const out = parseGuide(
      "## Tests\nwhy\nFiles: web/src/query_notification_subscriptions.test.ts",
      FILES,
    );
    expect(out.sections[0].files).toEqual([
      "web/src/query_notification_subscriptions.test.ts",
    ]);
  });

  it("gives a file to the first section that claims it, so no diff renders twice", () => {
    const out = parseGuide(
      "## A\nwhy\nFiles: server/scheduler.ts\n\n## B\nalso\nFiles: server/scheduler.ts, web/src/App.tsx",
      FILES,
    );
    expect(out.sections[0].files).toEqual(["server/scheduler.ts"]);
    expect(out.sections[1].files).toEqual(["web/src/App.tsx"]);
  });

  it("drops a generic document title but keeps a real first heading", () => {
    expect(parseGuide("# Reading guide\n\nwhat it does\n", FILES).intro).toBe(
      "what it does",
    );
    expect(parseGuide("# The scheduler\nwhy\n", FILES).sections[0].title).toBe(
      "The scheduler",
    );
  });

  it("treats a heading that is itself a path as a one-file section", () => {
    const out = parseGuide("## server/scheduler.ts\nthe core\n", FILES);
    expect(out.sections[0].files).toEqual(["server/scheduler.ts"]);
  });

  it("falls back to backticked paths in the prose when there is no Files line", () => {
    const out = parseGuide("## S\nAll of `server/scheduler.ts` is new.\n", FILES);
    expect(out.sections[0].files).toEqual(["server/scheduler.ts"]);
  });

  it("ignores headings and file lists inside a fenced block", () => {
    const out = parseGuide(
      "## S\nwhy\n\n```md\n## Not a section\nFiles: web/src/App.tsx\n```\n",
      FILES,
    );
    expect(out.sections).toHaveLength(1);
    expect(out.sections[0].files).toEqual([]);
    expect(out.leftover).toContain("web/src/App.tsx");
  });

  it("returns the whole diff as leftover when there is no guide yet", () => {
    const out = parseGuide("", FILES);
    expect(out.sections).toEqual([]);
    expect(out.intro).toBe("");
    expect(out.leftover).toEqual(FILES);
  });

  it("keeps prose that mentions no file as a section without diffs", () => {
    const out = parseGuide("## Risks\nthe cache can go stale.\n", FILES);
    expect(out.sections[0].files).toEqual([]);
    expect(out.sections[0].body).toContain("stale");
  });
});
